trigger:
- none

stages:
  - stage: 'LinuxTemplate'
    dependsOn: []
    displayName: 'Linux Template'

    jobs:
      - job: 'terraforminit'
        displayName: 'Terraform Init'
        pool: Self-Hosted

        steps:
          - task: CmdLine@2       
            inputs:
              script: |
                terraform init -backend-config="/terraform/variables/backend.tf"
              workingDirectory: '$(System.DefaultWorkingDirectory)/linux'  

      - job: 'terraformplan'
        dependsOn: terraforminit
        displayName: 'Terraform Plan' 
        pool: Self-Hosted

        steps:
          - task: CmdLine@2
            inputs:
              script: |
                terraform plan -var-file="/terraform/variables/terraform-esxi-vars/linux_template.tfvars"
              workingDirectory: '$(System.DefaultWorkingDirectory)/linux'
          - checkout: none

      - job: 'terraformapply'
        dependsOn: terraformplan
        displayName: 'Terraform Apply' 
        pool: Self-Hosted

        steps:
          - task: CmdLine@2
            inputs:
              script: |
                terraform apply -var-file="/terraform/variables/terraform-esxi-vars/linux_template.tfvars" -auto-approve
              workingDirectory: '$(System.DefaultWorkingDirectory)/linux'
          - checkout: none

  - stage: 'WindowsTemplate'
    dependsOn: []
    displayName: 'Windows Template'
      
    jobs:
      - job: 'terraforminit'
        displayName: 'Terraform Init'
        pool: Self-Hosted
      
        steps:
          - task: CmdLine@2       
            inputs:
              script: |
                terraform init -backend-config="/terraform/variables/backend.tf"
              workingDirectory: '$(System.DefaultWorkingDirectory)/windows'
      
      - job: 'terraformplan'
        dependsOn: terraforminit
        displayName: 'Terraform Plan' 
        pool: Self-Hosted
      
        steps:
          - task: CmdLine@2
            inputs:
              script: |
                terraform plan -var-file="/terraform/variables/terraform-esxi-vars/windows_template.tfvars"
              workingDirectory: '$(System.DefaultWorkingDirectory)/windows'
          - checkout: none
      
      - job: 'terraformapply'
        dependsOn: terraformplan
        displayName: 'Terraform Apply' 
        pool: Self-Hosted
      
        steps:
          - task: CmdLine@2
            inputs:
              script: |
                terraform apply -var-file="/terraform/variables/terraform-esxi-vars/windows_template.tfvars" -auto-approve
              workingDirectory: '$(System.DefaultWorkingDirectory)/windows'
          - checkout: none

    
          
