trigger:
- none

jobs:
  - job: 'terraforminit'
    displayName: 'Terraform Init'
    pool: Self-Hosted
    steps:
    - task: CmdLine@2       
      inputs:
        script: |
          terraform init

  - job: 'terraformplan'
    dependsOn: terraforminit
    displayName: 'Terraform Plan' 
    pool: Self-Hosted
    steps:
    - task: CmdLine@2
      inputs:
        script: |
          terraform plan -var-file="/terraform/variables/terraform-esxi-vars/linux_template.tfvars"
    - checkout: none

  - job: 'terraformapply'
    dependsOn: terraformplan
    displayName: 'Terraform Apply' 
    pool: Self-Hosted
    steps:
    - task: CmdLine@2
      inputs:
        script: |
          terraform apply -var-file="/terraform/variables/terraform-esxi-vars/linux_template.tfvars" -auto-approve
    - checkout: none
