trigger:
- none

jobs:
  - job: 'terraforminit'
    displayName: 'Terraform Init'
    pool: Self-Hosted
    steps:
    - task: CmdLine@2       
      inputs:
        script: |
          terraform init
        workingDirectory: $(System.DefaultWorkingDirectory)

  - job: 'terraformplan'
    dependsOn: terraforminit
    displayName: 'Terraform Plan' 
    pool: Self-Hosted
    steps:
    - task: CmdLine@2
      inputs:
        script: |
          terraform plan
        workingDirectory: $(System.DefaultWorkingDirectory)

  - job: 'terraformapply'
    dependsOn: terraformplan
    displayName: 'Terraform Apply' 
    pool: Self-Hosted
    steps:
    - task: CmdLine@2
      inputs:
        script: |
          terraform apply -var-file="/terraform/linux_template.tfvars" -auto-approve
        workingDirectory: $(System.DefaultWorkingDirectory)
