#cloud-config

instance-id: #{docker_guest_name}#
local-hostname: #{docker_guest_name}#
network:
  version: 2
  renderer: networkd
  ethernets:
    ens33:
      dhcp4: no
      addresses:
        - #{docker_ip_address}#/24
      routes:
        - to: default
          via: #{production_network_gateway}# 
      nameservers:
        addresses:
          - #{dns_server_01}#
          - #{dns_server_02}#
        search:
          - #{dns_domain}#
