instance-id: #{k3s02_guest_name}#
local-hostname: #{k3s02_guest_name}#
network:
  version: 2
  ethernets:
    nics:
      match:
        name: ens*
      dhcp4: false
      addresses:
        - #{k3s_02_ip_address}#
      gateway4: #{production_network_gateway}#
      nameservers:
        addresses:
          - #{dns_server_01}#
          - #{dns_server_02}#
        search:
          - #{dns_domain}#
