name: Host 02 Production CI

on:
  workflow_dispatch: 
    
permissions:
  contents: write
  issues: write

jobs:
  init_and_plan:
    name: Terraform Init and Plan
    runs-on: Self-Hosted
    environment: "Host 02 Production"

    outputs:
      planExitcode: ${{ steps.terraformPlan.outputs.exitcode }}

    steps:

      - name: Checkout 🔔
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Map Secrets to Environment Variables 🗺️ 
        uses: oNaiPs/secrets-to-env-action@ec46a22bfc9b37e014b627b3208b07eb8909ea0f # v1.5
        with:
            secrets: ${{ toJSON(secrets) }}        

      - name: Replace Tokens 🪙
        uses: cschleiden/replace-tokens@4d5a042c84c3568b3858b7af9394923d2d5195c9 # v1.3
        with:
          files: '["./production/host_02/**/*"]'

      - name: Install NodeJS 🖥️   
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 20

      - name: Install Terraform ⛰️
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3

      - name: Terraform Init 🏃
        id: terraformInit
        run: terraform init
        working-directory: ./production/host_02

      - name: Terraform Plan 🗺️
        id: terraformPlan
        run: |
          terraform plan -input=false -no-color -out ${{ github.sha }}.tfplan -detailed-exitcode 
        working-directory: ./production/host_02

      - name: Cache Terraform Plan 📦
        uses: actions/cache/save@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
        with:
          path: ./production/host_02/**
          key: ${{ github.sha }}

  apply:
    name: Terraform Apply
    needs:
      - init_and_plan
    if: github.event_name != 'pull_request' && needs.init_and_plan.outputs.planExitcode == 2
    runs-on: Self-Hosted

    steps:

      - name: Install Docker
        uses: crazy-max/ghaction-setup-docker@635d07c09dc2b52072362e9bb37e7e789767106d # v3

      - name: Manual Approval 🚦
        uses: trstringer/manual-approval@9f5e5d6bc511762e17f849775a3c56bdea6b4493 # v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: data-tangles
          minimum-approvals: 1
          issue-title: "Terraform Apply"
          issue-body: "Please approve or deny the Terraform Apply operation"
          exclude-workflow-initiator-as-approver: false

      - name: Checkout 🔔
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Restore Terraform Plan 🗺️
        uses: actions/cache/restore@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
        with:
          path: ./production/host_02/**
          key: ${{ github.sha }}

      - name: Install Terraform ⛰️
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3

      - name: Terraform Apply 🚀
        run: terraform apply ${{ github.sha }}.tfplan
        working-directory: ./production/host_02

